---
title: Aguara Demo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title-bold: Demo
title-normal: por Aguara
email: info@aguara.io
description: 'Tema responsive de demostración '
baseurl: "/"
url: 
author: 
street_address: Roque Centurion Miranda
city: Asuncion
state: 
zip_code: 55555
country: Paraguay
phone: "(0981)419228"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jemoji
tiles-source: posts
tiles-count: 6
500px_url: 
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/109498539741249689074
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/mart%C3%ADn-cubilla-451962122
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/martincubilla
markdown: kramdown
twitter:
  username: martincubilla
facebook:
  app_id: 
  publisher: 
  admins: 
logo: "/uploads/2-19d3bf.jpg"
google_site_verification: 
